require("heatshrink").decompress(
  atob(
    "kEgwkEogAvmYAFkQAFolDB5skBwwPHkQPPAA8RAByTHB6ESFYoFBkMBAYQPEkIPEkQPGBoQDCEgIPBkIHBB5IdBB4MCF4o/EB5Q/EB5A1CF5gPGJ5BvPR5y/ed58zAAwXHB+VEABAPSBhIAl"
  )
);
